### ISSUE TITLE
except: in comments

### ISSUE THREAD

**Issue by gforcada** [elijahandrews/flake8-blind-except#3]
It would be great if flake8-blind-except could handle the case that a inline or multiline comment has a `except:` in it.

As _except_ is a regular English word is not so uncommon to have it on comments and maybe (happened to me) followed by a colon.

**Comment by jayvdb** [comment]
I have a docstring where it is (basically) mandatory to have except:

https://github.com/wikimedia/pywikibot-core/blob/master/scripts/add_text.py#L53

**Comment by xZise** [comment]
If it is using `ast` it could only find instances in the code itself:

```
try:
    pass
except ValueError:
    pass
```

There `p.body[0].handlers[0].type.id` returns `ValueError` while in the next example `p.body[0].handlers[0].type` it returns None.

```
try:
    pass
except ValueError:
    pass
```

**Comment by jayvdb** [comment]
Also in comments, especially doctest, it is 'simpler' (and easier to read) if blind exceptions are used:

https://github.com/PyCQA/pep8/blob/master/pep8.py#L867

**Comment by jayvdb** [comment]
fwiw, noqa is supported and can be used as a workaround for this problem.

**Comment by elijahandrews** [comment]
Hello, sorry I haven't addressed this sooner. I didn't realize that people were using this! I think @xZise has the right idea. I'll take a stab at it sometime soon.

**Comment by elijahandrews** [comment]
I'm not working on much Python these days, so realistically I won't be getting around to this anytime soon. PRs are welcome though!
